### ISSUE TITLE
[mi-label] Test B12.1 Bug Fixes from Sprints 15 and 16

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#10]
## 🟢 Issues Ready For I&T

- [ ] https://github.com/nasa-pds/mi-label/issues/21

**Comment by gxtchen** [comment]
This can mark as closed.

**Comment by jordanpadams** [comment]
@gxtchen can you please add a copy or link to the test report here so we have some traceability?
