### ISSUE TITLE
[registry-api] Test B12.1 Bug Fixes and Improvements from Sprints 15 and 16

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#11]
## 🟢 Issues Ready For I&T

- [ ] https://github.com/NASA-PDS/pds-registry-app/issues/205 
- [ ] https://github.com/nasa-pds/pds-api/issues/74

**Comment by gxtchen** [comment]
@jordanpadams @viviant100  
Hi Jordan,
I need instructions to test the AWS LB and Secrets Manager. Please provide instructions on how to test registry-api-service#52 and registry-api-service#81. Using the AWS LB and AWS Secrets Manager is new to me.

Thanks
Gary

**Comment by jordanpadams** [comment]
@jimmie ☝️ 

@gxtchen we may need to table testing of that ticket until it is sufficiently documented how to set that up with Harvest / Registry Manager

**Comment by jordanpadams** [comment]
@gxtchen actually, after reviewing, I removed from I&T. this should be tested as part of a broader requirement to be able to ingest data to an AWS registry. that will verify that the secrets manager worked.

**Comment by jordanpadams** [comment]
@gxtchen also removed https://github.com/nasa-pds/registry-api-service/issues/81 from this ticket, as again, this needs to be part of some broader testing for testing that cross-cluster search works across the node registries. will put that together later on.

**Comment by jpl-jengelke** [comment]
@jordanpadams What sprint is this tied to? 15 or 16?
