### ISSUE TITLE
[doi-service] Test B12.1 Bug Fixes and Improvements from Sprints 15 and 16

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#12]
## 🟢 Issues Ready For I&T

- [x] https://github.com/nasa-pds/pds-doi-service/issues/273
- [x] https://github.com/nasa-pds/pds-doi-service/issues/223
- [x] https://github.com/nasa-pds/pds-doi-service/issues/278
- [x] https://github.com/nasa-pds/pds-doi-service/issues/279
- [x] https://github.com/nasa-pds/pds-doi-service/issues/289

**Comment by gxtchen** [comment]
Finished testing these 5 tickets, all passed.

**Comment by jordanpadams** [comment]
@gxtchen can you please add a copy or link to the test report here so we have some traceability?

**Comment by gxtchen** [comment]
Here is the link to testrail test results. https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/14016&group_by=cases:section_id&group_order=asc
