### ISSUE TITLE
[doi-search] Test B12.1 Enhancements to DOI Search Component

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#14]
## 🟢 Issues Ready For I&T

- [ ] Parent theme: https://github.com/nasa-pds/pds-wds-react/issues/13

See sub-tasks for enhancements. The DOI Search can be either deployed as it's own separate interface that queries the DOI Service API, or it can also be tested on the operational deployment here: https://pds.nasa.gov/tools/doi/

**Comment by gxtchen** [comment]
Test Passed. https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/14269&group_by=cases:section_id&group_order=asc
