### ISSUE TITLE
Add all test data from validation sprint #15 & 16 to regression test

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/system-i-n-t#17]
1. Start with smaller data from repo
2. Work on the big data using the pds-int node setup by SA
3. Complete prototype development in XMLs

**Comment by jpl-jengelke** [comment]
The PDS Jenkins is not functioning as of today. 

Sprint 15 is complete in CAE Jenkins. Sprint 16 is in progress, but is hoped to complete with both 15/16 together on PDS-INT. Waiting for Docker configuration.

**Comment by jpl-jengelke** [comment]
This is complete.
