### ISSUE TITLE
Sprint ending 5/26 Tasks

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#21]
## 🟢 Issues Ready For I&T

- [ ] https://github.com/nasa-pds/harvest/issues/90
- [ ] https://github.com/nasa-pds/doi-ui/issues/130
- [x] https://github.com/nasa-pds/registry-api/issues/121
- [x] https://github.com/nasa-pds/pds-api/issues/129
   - [x] https://github.com/nasa-pds/pds-api/issues/169
   - [x] https://github.com/nasa-pds/pds-api/issues/137
- [x] https://github.com/nasa-pds/pds-api/issues/158
- [x] https://github.com/nasa-pds/pds-api-client/issues/14

**Comment by viviant100** [comment]
Test completed with TestRail result in [system-i-n-t#21](https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/15925&group_by=cases:section_id&group_order=asc).   

nasa-pds/harvest#90 & nasa-pds/doi-ui#130 failed - 2 new I&T bug tickets are created:

- https://github.com/NASA-PDS/pds-api/issues/195

- https://github.com/NASA-PDS/harvest/issues/94
