### ISSUE TITLE
[registry] Sprint ending 6/16 Tasks

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/system-i-n-t#25]
## 🟢 Issues Ready For I&T

- [ ] https://github.com/nasa-pds/doi-service/issues/249 (link with DOIs)
- [ ] https://github.com/nasa-pds/registry/issues/69
- [ ] https://github.com/nasa-pds/registry-api/issues/109

**Comment by gxtchen** [comment]
All three tickets verified.
