### ISSUE TITLE
Sprint ending 07/28 I&T tasks

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/system-i-n-t#27]
## 🟢 Issues Ready For I&T

PDS API:
- [x] https://github.com/NASA-PDS/pds-api/issues/203
- [x] https://github.com/nasa-pds/pds-api/issues/191
- [x] https://github.com/nasa-pds/registry-api/issues/134
- [x] https://github.com/nasa-pds/registry-api/issues/152
- [x] https://github.com/nasa-pds/registry-api/issues/162
- ~[ ] https://github.com/NASA-PDS/pds-api/issues/60~

Harvest:
- [x] https://github.com/nasa-pds/harvest/issues/96

PDS4 Information Model
- [x] https://github.com/nasa-pds/pds4-information-model/issues/468

**Comment by gxtchen** [comment]
@tloubrieu-jpl Can you state which version I should be testing for each tools in this sprint? thx

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen , I added comments in the tickets to be explicit on which version to use for test.
Note that I'll be on paternity leave for 12 weeks from 08-05, you should contact @jimmie or @jordanpadams for these questions while I will be away. Thanks
