### ISSUE TITLE
Verify Registry API/OpenSearch work with manually created label 

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/system-i-n-t#40]
## 🟢 Issues Ready For I&T
Add the label with bogus data file in I&T test suite to verify it doesn't crash Registry API/OpenSearch (per [slack](https://jpl.slack.com/archives/GCGR1R3A4/p1679516406541239?thread_ts=1679510500.784749&cid=GCGR1R3A4) message)

example:
- **data** file:  https://pds-geosciences.wustl.edu/m2020/urn-nasa-pds-mars2020_sherloc/data_raw/sol_00004/SS__0004_0667298185_056ECA__0010052SRLC10002_0_____J10.xml 
- **label** references a product that'll need to be created: SS__0004_0667298185_056ECA__0010052SRLC10002_0_____J10.CSV (can be an empty file)
- (Optional) To test it in validate tool, use the --skip-content-validation flag 

Related ticket: [API crashes with JVM memory error on data sets with very large labels (>1MB)](https://github.com/NASA-PDS/registry-api/issues/296#top) #296

**Comment by jordanpadams** [comment]
closing as wontfix. this will eventually come out when we fix the bug
