### ISSUE TITLE
[validate] Test Bug Fixes from 12.Roger.Bannister Sprint

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#5]
## 🟢 Issues Ready For I&T

- [x] https://github.com/NASA-PDS/validate/issues/372 
- [x] https://github.com/NASA-PDS/validate/issues/380
- [x] https://github.com/NASA-PDS/validate/issues/379
- [x] https://github.com/NASA-PDS/validate/issues/375
- [x] https://github.com/NASA-PDS/validate/issues/381

## 📜 Test Plan / Procedure

https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/12662&group_by=cases:section_id&group_order=asc

**Comment by viviant100** [comment]
Test results are documented in "I&T Sprint #5" milestone: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/12662&group_by=cases:section_id&group_order=asc

**Comment by jordanpadams** [comment]
closed per completion of I&T. see testing artifacts here: https://pds-engineering.jpl.nasa.gov/content/build_12.0_it_deliverables

**Comment by jordanpadams** [comment]
closed per completion of I&T. see testing artifacts here: https://pds-engineering.jpl.nasa.gov/content/build_12.0_it_deliverables
