### ISSUE TITLE
[validate] Test B12.1 Issues from Sprints 15 and 16

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#9]
## 🟢 Issues Ready For I&T

Catching up on closed validate issues since I&T began. Ignore those that were already included in B12.0
- [x] https://github.com/nasa-pds/validate/issues/349 
- [x] https://github.com/nasa-pds/validate/issues/416
- [x] https://github.com/nasa-pds/validate/issues/419
- [x] https://github.com/nasa-pds/validate/issues/423
- [x] https://github.com/nasa-pds/validate/issues/424

**Comment by jpl-jengelke** [comment]
These tests are complete. All passed. See results posted in individual tickets and in TestRail.

**Comment by viviant100** [comment]
TestRail results can be found here: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/suites/overview/193.
